version: '3.0'
services:
  db:
    image: "postgres:9.6"
    container_name: "db"
    ports:
      - "5432:5432"
  rails:
    image: "rails:latest"
    container_name: "rails"
    depends_on: ["db"]
    volumes:
      - "~/Desktop/backend-docker-palyground/testpostgre:/app"
    tty: true
    ports:
      - "3000:3000"
