#db:
#  image: "mysql:5.7"
#  container_name: "db"
#  environment:
#    - MYSQL_ROOT_PASSWORD=temppass
#  ports:
#    - "3306:3306"

rails:
  image: "ruby:2.3"
  container_name: "rails"
  volumes:
    - "~/Desktop/backend-docker-palyground/Gemfile:/app/Gemfile"
  tty: true
  ports:
    - "3000:3000"
