db:
  image: "postgres:9.6"
  container_name: "db"
#  environment:
#    - MYSQL_ROOT_PASSWORD=temppass
  ports:
    - "5432:5432"

#rails:
#  image: "rails2:latest"
#  container_name: "rails"
#  volumes:
#    - "~/Desktop/backend-docker-palyground/testpostgre:/app"
#  tty: true
#  ports:
#    - "3000:3000"
